//console.dir(document);
console.log(document.URL);
console.log(document.domain);
console.log(document.title);
//console.log(document.all);
console.log(document.doctype);
 document.all[10].textContent="hello";
 console.log(document.links);
 let headerTitle=document.getElementById("header_title");
 console.log(headerTitle);
 //headerTitle.textContent="goodbye";
 //headerTitle.innerText="goodbye";
 //headerTitle.style.borderBottom='solid 3px #000';
 //document.all[10].style.borderBottom="solid 3px #000"
//document.getElementById("header_title").textContent="hello";
// document.getElementsByClassName("list-group-item").style.color="green";
let items=document.getElementsByClassName("list-group-item");
console.log(items);
items[1].style.fontWeight='bold';
items[1].style.color='brown';
items[2].style.backgroundColor='green';
items[2].style.fontWeight='bold';
items[2].style.color='red';
items[3].style.fontWeight='bold';
items[3].style.color='blue';
items[0].style.fontWeight='bold';
items[4].style.fontWeight='bold';
items[4].style.color='yellow';
//console.log(document.getElementsByTagName('li'));
let k=document.getElementsByTagName('li');
console.log(k);
k[4].style.backgroundColor='black';
